### ISSUE TITLE
禁用 Want-Digest 标头

### ISSUE THREAD

**Issue by mogu1121** [myfreeer/aria2-build-msys2#10]
https://github.com/P3TERX/aria2-builder/
这个禁用了 Want-Digest 但是没有win版

**Comment by myfreeer** [comment]
`Want-Digest` 头在 [`HttpRequest::createRequest#L265`](https://github.com/aria2/aria2/blob/15cad965eb75c8b7f11bc2fc94354d1873bf6261/src/HttpRequest.cc#L265) 引入，受[noWantDigest_](https://github.com/aria2/aria2/blob/15cad965eb75c8b7f11bc2fc94354d1873bf6261/src/HttpRequest.cc#L250) 控制，noWantDigest_ 可通过 [`setNoWantDigest`](https://github.com/aria2/aria2/blob/15cad965eb75c8b7f11bc2fc94354d1873bf6261/src/HttpRequest.h#L235) 修改，但官方不能通过选项参数控制。
考虑增加选项参数控制而不是简单的禁用或启用。

**Comment by myfreeer** [comment]
<https://github.com/myfreeer/aria2-build-msys2/releases/tag/1.35.0.1>

**Comment by mogu1121** [comment]
怎么才能统一在不同的目录使用配置文件
我之前用的官方版本统一在 %USERPROFILE%  + .aria2\aria2.conf
现在是 启动目录 + .config/aria2/aria2.conf

**Comment by myfreeer** [comment]
由于此编译版增加了一些配置项，与官方版本使用相同的配置文件可能影响对增加的配置项的定制。
可使用符号链接或硬链接，参考 `mklink` 命令

**Comment by mogu1121** [comment]
是不是也要启动目录存在链接才有用啊
