### ISSUE TITLE
朋友在未来的版本编译的时候能将  --with-http_v3_module 默认加上吗？

### ISSUE THREAD

**Issue by reyoreyo** [myfreeer/aria2-build-msys2#19]
朋友在未来的版本编译的时候能将  --with-http_v3_module 默认加上吗？

Could you please include the --with-http_v3_module option by default in the compilation for future versions?

Thank you!

**Comment by myfreeer** [comment]
I've searched over the whole aria2 repo and found nothing related to http3 for now. This repo contains build scripts, a big feature like this is out of the scope of this repo. Ask [aria2](https://github.com/aria2/aria2) upstream for this support, and in English.

我搜索了整个 aria2 版本库，暂时没有发现与 http3 相关的内容。这个软件源包含构建脚本，像这样的大功能不在这个软件源的范围之内。请向 [aria2](https://github.com/aria2/aria2)上游寻求支持，用英语。
