### ISSUE TITLE
“update path patch”的最新版，dht6.dat路径没改过来？

### ISSUE THREAD

**Issue by frdqx** [myfreeer/aria2-build-msys2#2]
6月5日`update path patch`的最新版，`aria2.conf`中不指定路径，`dht.dat`已默认显示在根目录，`dht6.dat`却仍在`.cacheD\aria2\`下。

`AriaNg`和`Aria2_WebUI`的设置中均如此显示，是改过来没生效吗？截图如下——

![aria2_webui](https://user-images.githubusercontent.com/38649948/41019292-956d3426-6990-11e8-8749-864f87044ed0.jpg)
![ariang](https://user-images.githubusercontent.com/38649948/41019293-9605b2be-6990-11e8-817c-f85548bbdac2.jpg)

**Comment by myfreeer** [comment]
在aria2c.exe所在文件夹新建名为`dht6.dat`的文件即可。

`dht6.dat`文件查找顺序：
1. `.aria2/dht6.dat`
2. 如果1不存在，`dht6.dat`
3. 如果2不存在，`.cache/aria2/dht6.dat`
