### ISSUE TITLE
cares这个文件路径访问不了

### ISSUE THREAD

**Issue by zhuigu** [myfreeer/aria2-build-msys2#20]
cares_ver="1.19.1"
wget -c --no-check-certificate "https://c-ares.haxx.se/download/c-ares-${cares_ver}.tar.gz"

**Comment by myfreeer** [comment]
Nice catch, seems upstream has changed the url to github release. Thanks for reporting.

**Comment by myfreeer** [comment]
https://github.com/myfreeer/aria2-build-msys2/commit/ce79080f2fc66aa4d233fd937cb58901c9f95087
