### ISSUE TITLE
有个疑问,我用原版aria2的时候cmd窗口不关闭

### ISSUE THREAD

**Issue by qasqasq12** [myfreeer/aria2-build-msys2#4]
把aria2c这个文件换成编译版后,cmd窗口就关闭了.

其他文件conf等都没变,这是什么原因呢?

我其实比较喜欢有cmd窗口,可以时不时看看情况,是否把conf里面的daemon=true改成daemon=false.就保留cmd窗口了?

哪为什么daemon=true用在原版窗口就不关闭呢?

**Comment by qasqasq12** [comment]
还真是把daemon=true改成daemon=false.就保留cmd窗口了.

奇怪的是为什么原版却保留窗口呢?

**Comment by myfreeer** [comment]
1. 官方 mingw 版不支持 daemon 参数 [aria2/README.mingw#L42@6c30b13a](https://github.com/aria2/aria2/blob/6c30b13a91646d5b9ed26d12806850d33ec6f94b/README.mingw#L42)
2. 本版通过 [patch](https://github.com/myfreeer/aria2-build-msys2/blob/master/aria2-0004-option_processing-make-use-of-deamon-on-mingw.patch) 支持
