### ISSUE TITLE
请问为什么在windows下，设置了disk-cache，还是会频繁写入？

### ISSUE THREAD

**Issue by MaxMadcc** [myfreeer/aria2-build-msys2#6]
file-allocation=prealloc
disk-cache=128M
enable-mmap=false
就是这些参数，设置之后还是会频繁写入。

**Comment by myfreeer** [comment]
本编译版未改动磁盘缓存相关逻辑，可能是[上游](https://github.com/aria2/aria2/issues)问题

**Comment by MaxMadcc** [comment]
应该是上游的问题

**Comment by urain39** [comment]
你好，我也遇到了相同的问题。我觉得可能是与prealloc预分配有关，如果把预分配模式改成falloc或者直接改成none禁用的话就不会出现频繁读写的问题了。

**Comment by urain39** [comment]
> 你好，我也遇到了相同的问题。我觉得可能是与prealloc预分配有关，如果把预分配模式改成falloc或者直接改成none禁用的话就不会出现频繁读写的问题了。

测试了一下，none模式下的disk-cache也没用（

**Comment by MaxMadcc** [comment]
> > 你好，我也遇到了相同的问题。我觉得可能是与prealloc预分配有关，如果把预分配模式改成falloc或者直接改成none禁用的话就不会出现频繁读写的问题了。
> 
> 测试了一下，none模式下的disk-cache也没用（

可能就是在windows下运行有问题
